In [4]:
import numpy as np
import functools
import operator as op

In [56]:
def scalar_sign(x):
    if x < 0.0:
        return -1
    if x > 0.0:
        return 1
    return 0.0

sign = np.vectorize(scalar_sign)

class BidirectionalAssociativeMemory(object):
    
    def __init__(self, x, y):
        self.weight = np.dot(x.T, y)
        
    def compute_forward(self, x):
        y = np.dot(x.T, self.weight)
        y = sign(y)
        return y.T.astype(np.float64)
    
    def compute_backwards(self, y):
        x = np.dot(self.weight.T, y)
        x = sign(y)
        return x.T.astype(np.float64)
        
    def retrieve(self, x):
        x0 = x.T 
        print(x0)
        y0 = self.compute_forward(x)
        print(y0)
        x1 = sign(np.dot(self.weight, y0))
        y1 = self.compute_forward(x1)
        p = 0
        converged = np.equal(x0, x1).all() and np.equal(y0, y1).all()
        while not converged:
            p += 1
            x0 = x1
            y0 = y1
            x1 = sign(np.dot(self.weight, y0))
            y1 = self.compute_forward(x1)
            converged = np.equal(x0, x1).all() and np.equal(y0, y1).all()
            if p > 10:
                break
        return (p, x1, y1)
            
    
        
    

In [57]:
x = np.array([
        [1,1,1,1,1,1],
        [-1,-1,-1,-1,-1,-1],
        [1,1,-1,-1,1,1],
        [-1,-1,1,1,-1,-1]
    ])

y = np.array([
        [1,1,1],
        [-1,-1,-1],
        [1,-1,1],
        [-1,1,-1]
    ])
network = BidirectionalAssociativeMemory(x, y)
print(x[0])
print(network.compute_backwards(x[0]))
print(network.compute_forward(x[0]))


[1 1 1 1 1 1]
[ 1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.]


In [58]:
network.retrieve(np.array([-1, 1, 1, 1, 1, 1]))

[-1  1  1  1  1  1]
[ 1.  1.  1.]


(1, array([1, 1, 1, 1, 1, 1]), array([ 1.,  1.,  1.]))