In [18]:
#network.compute(np.array([1, 1, 1]))


matrix([[ 4.,  4.,  4.]])

In [1]:
import numpy as np
import copy 
import functools
import operator as op

In [151]:
def scalar_sign(x):
    if x < 0.0:
        return -1
    if x > 0.0:
        return 1
    return 0.0

sign = np.vectorize(scalar_sign)

class Hopfield(object):
    
    def __init__(self, memories):
        self.memories = memories
        self.weight = (memories.T @ memories).astype(np.float64)
        s = memories.shape
        self.num_memories = s[0]
        self.length = s[1]
        self.correction = self.num_memories * np.identity(self.length)
        self.weight -= self.correction
        self.theta = np.zeros((self.length, 1)).astype(np.float64)
        
    def compute(self, x):
        y = sign(np.dot(self.weight, np.atleast_2d(x).T) - self.theta)
        return y.T.astype(np.float64)
    
    def test(self):
        for x in self.memories:
            y = self.compute(x)
            truth = (np.equal(x, y)).all()
            if not truth:
                print(x)
                print(y)
                return False
        return True
    
    
    
    def retrieve(self, x):
        y = self.compute(x)
        converged = np.equal(x, y).all()
        iteration = 0
        while True:
            iteration += 1
            print('Iteration ', iteration)
            x = np.squeeze(np.asarray(y))
            y = np.squeeze(np.asarray(self.compute(x)))
            converged = np.equal(x, y).all()
            if converged:
                break
            neuron = np.random.randint(self.length)
            delta_y = sign(np.array(np.dot(self.weight[neuron], y.T) - self.theta[neuron][0]).astype(np.float64))
            delta_y = delta_y[0][0]
            y[neuron] = delta_y
        return (y, iteration)
            
    

In [152]:
memories = np.matrix([
        [1, 1, 1],
        [-1, -1, -1],
    ])
network = Hopfield(memories)
x = np.array([-1, 1, 1])
network.retrieve(x)

Iteration  1
Iteration  2
Iteration  3


(array([ 1.,  1.,  1.]), 3)

In [121]:

np.dot(network.weight, np.array([1, 1, 1]).T)
sign(np.matrix([[4, 4, 4]]))

matrix([[1, 1, 1]])

In [122]:
network.compute(np.array([[1, 1, 1]]))

matrix([[ 1.,  1.,  1.]])

In [123]:
network.test()

True

In [124]:
x = np.array([-1, 1, 1])
network.compute(x)


matrix([[ 1.,  0.,  0.]])

In [112]:
network.retrieve(x)

Iteration  1
[[ 2.]]
2
[[ 1.  0.  0.]]


IndexError: index 2 is out of bounds for axis 0 with size 1

In [103]:
while not converged and iteration < max_iterations:
            y = np.squeeze(np.asarray(y))
            iteration += 1
            print('Iteration ', iteration)
            neuron = np.random.randint(self.length)
            delta_y = sign(np.array(np.dot(self.weight[neuron], y.T) - self.theta[neuron][0]).astype(np.float64))
            delta_y = delta_y[0][0]
            y_prime = copy.deepcopy(y)#np.squeeze(np.asarray(self.compute(y)))
            print(y)
            print(y_prime)
            converged = np.equal(y_prime, y).all()
            if not converged:
                y_prime[neuron] = delta
            y = y_prime
        return y



In [105]:
c[1][0]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [118]:
x = (np.matrix([[2]]))
x.A1[0]

2

In [43]:
b = np.array([[1, -1, 1, -1, 1]])
b = b.T @ b

In [44]:
c = np.array([[-1, 1, -1, 1, -1]])
c = c.T @ c

In [41]:
c

array([[ 1, -1,  1, -1,  1],
       [-1,  1, -1,  1, -1],
       [ 1, -1,  1, -1,  1],
       [-1,  1, -1,  1, -1],
       [ 1, -1,  1, -1,  1]])

In [45]:
a + b + c

array([[ 3, -1,  3, -1,  3],
       [-1,  3, -1,  3, -1],
       [ 3, -1,  3, -1,  3],
       [-1,  3, -1,  3, -1],
       [ 3, -1,  3, -1,  3]])

In [46]:
(a + b + c) - (3 * np.identity(5))

array([[ 0., -1.,  3., -1.,  3.],
       [-1.,  0., -1.,  3., -1.],
       [ 3., -1.,  0., -1.,  3.],
       [-1.,  3., -1.,  0., -1.],
       [ 3., -1.,  3., -1.,  0.]])

In [47]:
network.weight

matrix([[-2., -1.,  3., -1.,  3.],
        [-1., -2., -1.,  3., -1.],
        [ 3., -1., -2., -1.,  3.],
        [-1.,  3., -1., -2., -1.],
        [ 3., -1.,  3., -1., -2.]])