In [2]:
import numpy as np
import functools 
import operator as op

In [45]:
def distance(x, y):
    z = x - y
    d = np.linalg.norm(z)
    return d

def is_neighbour(x, y):
    d = distance(x, y)
    if d < 0.01:
        return True
    return False



class SelfOrganizingMap(object):
    
    def __init__(self, i, j, alpha=0.1, is_neighbour=is_neighbour):
        self.weights = []
        self.i = i
        self.j = j
        self.alpha = alpha
        self.is_neighbour = is_neighbour
        for _ in range(j):
            self.weights.append(np.random.random((1, i)))
        
    def get_vec(self, x):
        idx = min(range(self.j), key=lambda y: distance(x, self.weights[y]))
        return (idx, self.weights[idx])
    
    def get_neighbours(self, x):
        idxs = filter(lambda y: self.is_neighbour(x, self.weights[y]), range(self.j))
        return idxs
    
    def train(self, X, epochs=1000):
        for _ in range(epochs):
            for x in X:
                y_idx, y = self.get_vec(x)
                idxs = self.get_neighbours(y)
                for idx in idxs:
                    delta = (self.alpha * x - self.weights[idx])
                    self.weights[idx] += delta
    
        

In [46]:
X = np.array([
        [0.2, 0.9],
        [0.6, -0.2],
        [-0.7, -0.8]
    ])
m = SelfOrganizingMap(2, 10)
#m.train(X)
m.weights

[array([[ 0.50164582,  0.07066768]]),
 array([[ 0.71564937,  0.03913366]]),
 array([[ 0.37194821,  0.06714273]]),
 array([[ 0.41876724,  0.60075787]]),
 array([[ 0.63589785,  0.31081202]]),
 array([[ 0.22435659,  0.61971489]]),
 array([[ 0.19251918,  0.92960153]]),
 array([[ 0.12295358,  0.393484  ]]),
 array([[ 0.17920283,  0.02254849]]),
 array([[ 0.16855686,  0.4247714 ]])]

In [47]:
m.train(X)

In [48]:
m.weights

[array([[ 0.06, -0.02]]),
 array([[-0.07, -0.08]]),
 array([[ 0.06, -0.02]]),
 array([[ 0.02,  0.09]]),
 array([[ 0.06, -0.02]]),
 array([[ 0.02,  0.09]]),
 array([[ 0.02,  0.09]]),
 array([[ 0.02,  0.09]]),
 array([[ 0.06, -0.02]]),
 array([[ 0.02,  0.09]])]

In [50]:
m.get_vec(np.array([12, 0.9]))

(0, array([[ 0.06, -0.02]]))

In [36]:
m.weights

[array([[-0.07, -0.08]]), array([[-0.07, -0.08]])]